module.exports = {
  sl_chrome_26: {
    base: 'SauceLabs',
    browserName: 'chrome',
    version: '26',
  },
  sl_chrome_56: {
    base: 'SauceLabs',
    browserName: 'chrome',
    version: '56',
  },
  sl_firefox_16: {
    base: 'SauceLabs',
    browserName: 'firefox',
    version: '16',
  },
  sl_firefox_51: {
    base: 'SauceLabs',
    browserName: 'firefox',
    version: '51',
  },
  sl_ie_10: {
    base: 'SauceLabs',
    browserName: 'internet explorer',
    platform: 'Windows 7',
    version: '10',
  },
  sl_ie_11: {
    base: 'SauceLabs',
    browserName: 'internet explorer',
    platform: 'Windows 8.1',
    version: '11',
  },
  sl_edge_13: {
    base: 'SauceLabs',
    browserName: 'MicrosoftEdge',
    platform: 'Windows 10',
    version: '13.10586',
  },
  sl_edge_14: {
    base: 'SauceLabs',
    browserName: 'MicrosoftEdge',
    platform: 'Windows 10',
    version: '14.14393',
  },
  sl_safari_7: {
    base: 'SauceLabs',
    browserName: 'safari',
    platform: 'OS X 10.9',
    version: '7.0',
  },
  sl_safari_10: {
    base: 'SauceLabs',
    browserName: 'safari',
    platform: 'macOS 10.12',
    version: '10.0',
  },
  sl_iphone_4s: {
    base: 'SauceLabs',
    browserName: 'Safari',
    platformName: 'iOS',
    platformVersion: '8.1',
    deviceName: 'iPhone 4s Simulator',
    appiumVersion: '1.6.3',
  },
  sl_iphone_7: {
    base: 'SauceLabs',
    browserName: 'Safari',
    platformName: 'iOS',
    platformVersion: '10.2',
    deviceName: 'iPhone 7 Plus Simulator',
    appiumVersion: '1.6.3',
  },
  sl_android_5_1: {
    base: 'SauceLabs',
    browserName: 'Browser',
    platformName: 'Android',
    platformVersion: '5.1',
    deviceName: 'Android Emulator',
    appiumVersion: '1.5.3',
  },
}
